## Q1_A&B

<div style="display:block;width:100%;margin:auto;" direction=rtl align=center><br><br>
    <div  style="width:100%;margin:100;display:block;background-color:#fff0;"  display=block align=center>
        <table style="border-style:hidden;border-collapse:collapse;">
            <tr>
                <td  style="border: none!important;">
        <img width=130 align=right src="https://i.ibb.co/yXKQmtZ/logo1.png" style="margin:0;" />
                </td>
                <td style="text-align:center;border: none!important;">
                <h1 align=center><font size=5 color="#045F5F"> <b>Deep Learning (Fall 2023)</b><br><br><b>Homework-1</i><br><br><h1><h3>Mcculloch-Pitts-Q1</i></font></h3>
                </td>
                <td style="border: none!important;">
        <img width=170 align=left  src="https://i.ibb.co/wLjqFkw/logo2.png" style="margin:0;" />
                </td>
            </tr>
        </table>
    
</div>
<br>
<font size=3 color="#045F5F">Mohammad Javad Ranjbar<br></font><br>
<font size=3 color="#045F5F">Behrad Mosaie<br></font><br>

In [1]:
import numpy as np
import itertools
class McCulloch_Pitts_neuron():

  def __init__(self , weights , threshold):
    self.weights = weights    #define weights
    self.threshold = threshold    #define threshold

  def model(self , x):
    #define model with threshold
    if np.dot(self.weights, x) >= self.threshold:
      return 1
    else:
      return 0
num_cols = 7
num_rows = 128

arr = np.zeros((num_rows, num_cols), dtype=int)

for i in range(2**num_cols):
  row = np.binary_repr(i, width=num_cols)
  row = [int(x) for x in row]

  arr[i] = row

X= np.array(arr)
print(X.shape , X.dtype, X )

(128, 7) int64 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1]
 [0 0 0 0 1 0 0]
 [0 0 0 0 1 0 1]
 [0 0 0 0 1 1 0]
 [0 0 0 0 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 1]
 [0 0 0 1 0 1 0]
 [0 0 0 1 0 1 1]
 [0 0 0 1 1 0 0]
 [0 0 0 1 1 0 1]
 [0 0 0 1 1 1 0]
 [0 0 0 1 1 1 1]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 1]
 [0 0 1 0 0 1 0]
 [0 0 1 0 0 1 1]
 [0 0 1 0 1 0 0]
 [0 0 1 0 1 0 1]
 [0 0 1 0 1 1 0]
 [0 0 1 0 1 1 1]
 [0 0 1 1 0 0 0]
 [0 0 1 1 0 0 1]
 [0 0 1 1 0 1 0]
 [0 0 1 1 0 1 1]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 1]
 [0 0 1 1 1 1 0]
 [0 0 1 1 1 1 1]
 [0 1 0 0 0 0 0]
 [0 1 0 0 0 0 1]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 1]
 [0 1 0 0 1 0 0]
 [0 1 0 0 1 0 1]
 [0 1 0 0 1 1 0]
 [0 1 0 0 1 1 1]
 [0 1 0 1 0 0 0]
 [0 1 0 1 0 0 1]
 [0 1 0 1 0 1 0]
 [0 1 0 1 0 1 1]
 [0 1 0 1 1 0 0]
 [0 1 0 1 1 0 1]
 [0 1 0 1 1 1 0]
 [0 1 0 1 1 1 1]
 [0 1 1 0 0 0 0]
 [0 1 1 0 0 0 1]
 [0 1 1 0 0 1 0]
 [0 1 1 0 0 1 1]
 [0 1 1 0 1 0 0]
 [0 1 1 0 1 0 1]
 [0 1 1 0 1 1 0]
 [0 1 1 0 1 1 1]
 [0 1 1 1 0 0 0]
 [0 1 1 1 0 0 1]

In [2]:
n6 = McCulloch_Pitts_neuron([1,-1,1,1,1,1,1], 6)
n7 = McCulloch_Pitts_neuron([1,1,1,-1,-1,-1,-1], 3)
n8 = McCulloch_Pitts_neuron([1,1,1,1,1,1,1], 7)
n9 = McCulloch_Pitts_neuron([1,1,1,1,-1,1,1], 6)
for inp in X:

  o1 = n6.model(inp)
  o2 = n7.model(inp)
  o3 = n8.model(inp)
  o4 = n9.model(inp)

  if o1:
    print(inp, "- Digit 6")
  elif o2:
    print(inp, "- Digit 7")
  elif o3:
    print(inp, "- Digit 8")
  elif o4:
    print(inp, "- Digit 9")
  else:
    print(inp, "- No digit detected")

[0 0 0 0 0 0 0] - No digit detected
[0 0 0 0 0 0 1] - No digit detected
[0 0 0 0 0 1 0] - No digit detected
[0 0 0 0 0 1 1] - No digit detected
[0 0 0 0 1 0 0] - No digit detected
[0 0 0 0 1 0 1] - No digit detected
[0 0 0 0 1 1 0] - No digit detected
[0 0 0 0 1 1 1] - No digit detected
[0 0 0 1 0 0 0] - No digit detected
[0 0 0 1 0 0 1] - No digit detected
[0 0 0 1 0 1 0] - No digit detected
[0 0 0 1 0 1 1] - No digit detected
[0 0 0 1 1 0 0] - No digit detected
[0 0 0 1 1 0 1] - No digit detected
[0 0 0 1 1 1 0] - No digit detected
[0 0 0 1 1 1 1] - No digit detected
[0 0 1 0 0 0 0] - No digit detected
[0 0 1 0 0 0 1] - No digit detected
[0 0 1 0 0 1 0] - No digit detected
[0 0 1 0 0 1 1] - No digit detected
[0 0 1 0 1 0 0] - No digit detected
[0 0 1 0 1 0 1] - No digit detected
[0 0 1 0 1 1 0] - No digit detected
[0 0 1 0 1 1 1] - No digit detected
[0 0 1 1 0 0 0] - No digit detected
[0 0 1 1 0 0 1] - No digit detected
[0 0 1 1 0 1 0] - No digit detected
[0 0 1 1 0 1 1] - No digit d

## Q1_C

In [3]:
h0 = McCulloch_Pitts_neuron([1,0,0,1,1,1,0], 4) #similar 6
h1 = McCulloch_Pitts_neuron([1,1,1,0,0,0,1], 4) #similar 9

X1= np.array([[1,0,1,1,1,1,1],[1,1,1,0,0,0,0],[1,1,1,1,1,1,1],[1,1,1,1,0,1,1]])

n66 = McCulloch_Pitts_neuron([1,-1],1)
n77 = McCulloch_Pitts_neuron([-1,-1],0)
n88 = McCulloch_Pitts_neuron([1,1],2)
n99 = McCulloch_Pitts_neuron([-1,1],1)
for inp in X1:
  z1= h0.model(inp)
  z2= h1.model(inp)
  X2=[z1,z2]
  print("output of hidden neurons are:  " , X2)
  o1= n66.model([z1,z2])
  o2= n77.model([z1,z2])
  o3= n88.model([z1,z2])
  o4= n99.model([z1,z2])

  if z1==z2!=0:
    print(inp, "- 8")
  elif z1:
    print(inp, "- similar to 6")
  elif z2:
    print(inp, "- similar to 9")
  else:
    print(inp, "- No digit detected")
  if o1:
    print(inp, "- Digit 6")
  elif o2:
    print(inp, "- Digit 7")
  elif o3:
    print(inp, "- Digit 8")
  elif o4:
    print(inp, "- Digit 9")
  else:
    print(inp, "- No digit detected")


output of hidden neurons are:   [1, 0]
[1 0 1 1 1 1 1] - similar to 6
[1 0 1 1 1 1 1] - Digit 6
output of hidden neurons are:   [0, 0]
[1 1 1 0 0 0 0] - No digit detected
[1 1 1 0 0 0 0] - Digit 7
output of hidden neurons are:   [1, 1]
[1 1 1 1 1 1 1] - 8
[1 1 1 1 1 1 1] - Digit 8
output of hidden neurons are:   [0, 1]
[1 1 1 1 0 1 1] - similar to 9
[1 1 1 1 0 1 1] - Digit 9
